site_name: Windower Documentation
site_url: https://docs.windower.net
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Addons (v4): 
      - addons_v4/index.md
      - addons_v4/battlemod.md
      - addons_v4/gearswap.md
  - Plugins (v4): index.md
  - Addons (v5): index.md
theme:
  name: material
  palette:
    primary: green
    accent: green
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/Windower/docs
repo_name: Windower/docs
copyright: Copyright &copy; 2022 Windower Development Team
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Windower
    - icon: fontawesome/brands/discord
      link: https://discord.gg/aUrHCvk
